### ISSUE TITLE
unable to configure.

### ISSUE THREAD

**Issue by nmsoares** [danielwelch/hassio-dropbox-sync#1]
Hi,
I've just install dropbox-sync on hassio.io 0.65 and got this error while saving the configuration in the Hassio dashboard.

not a valid value for dictionary value @ data['options']. Got {'oauth_access_token': 'xxxxxxxxxxxxxxxx', 'output': '', 'keep_last': ''}
(I've removed the dropbox token for security reasons)

Can you help ?
Thanks

**Comment by danielwelch** [comment]
Can you tell me what version of the add-on you have installed?

**Comment by macstibs** [comment]
Same error here 
V 1.1.1

Thanks.

**Comment by macstibs** [comment]
Adding a number to Keep_last clears the error and allows it to launch

**Comment by danielwelch** [comment]
In version 1.1.1, I made the keep_last parameter optional. So you can either set it to a number, or remove it entirely if you don’t want to use the keep_last functionality. Either way should remove the error.

**Comment by danielwelch** [comment]
In the next version, I probably won’t include the keep_last option in the default config, so this issue won’t occur “by default” unless the necessary changes are made.

**Comment by macstibs** [comment]
For whatever reason, if  I try to remove the Keep_last option, it won't
save and start properly



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

**Comment by nmsoares** [comment]
version 1.1.0 and also version 1.1.1.
Same error in both versions.
If you remove the last parameter "keep_last" you also get the same error.

**Comment by danielwelch** [comment]
@nmsoares @macstibs 
Hopefully this issue is resolved with the release of v1.1.2. Please try it out and let me know.

Sorry for the problem, the hass.io dev docs were a little unclear to me around optional parameter definitions so there's a little trial and error here, but v1.1.2 is working in my local testing both with the `keep_last` parameter set as well as with the parameter omitted entirely.

**Comment by danielwelch** [comment]
Closing for now, reopen if problem persists.
