### ISSUE TITLE
Hassio Config missing in automatic backup

### ISSUE THREAD

**Issue by TheZoker** [danielwelch/hassio-dropbox-sync#13]
When the backup is created by your script, the `Home Assistant configuration` is missing:
![screenshot_2018 10 30_16h20m08s_006_](https://user-images.githubusercontent.com/1368405/47729189-ff6ae700-dc5f-11e8-8b50-aed7742fc76e.png)

When I create the backup manually, the folder is there:
![screenshot_2018 10 30_16h19m57s_005_](https://user-images.githubusercontent.com/1368405/47729188-ff6ae700-dc5f-11e8-9c53-dbe1d8bbe11a.png)

**Comment by danielwelch** [comment]
What script are you referring to? This add-on doesn’t create snapshots (which is what I assume you mean when you say backups).

**Comment by TheZoker** [comment]
Of of course you're right. Seems to be a issue with backup via script...
