### ISSUE TITLE
*** FAILED An error occurred requesting /chunked_upload

### ISSUE THREAD

**Issue by woody4165** [danielwelch/hassio-dropbox-sync#14]
Hi all

I've installed this addon and I'm getting this error.

Log is:

```
[Info] Files will be uploaded to: /hass_b3_backup/
[Info] Saving OAUTH_ACCESS_TOKEN to /etc/uploader.conf
[Info] Listening for messages via stdin service call...
{"command": "upload"}
[Info] Received message with command upload
[Info] Uploading all .tar files in /backup (skipping those already in Dropbox)
 > Uploading "/backup/14c13bf3.tar" to "/hass_b3_backup/yyyyyyyyy.tar" by 6 chunks *** FAILED
An error occurred requesting /chunked_upload
```

My config is:

```
{
  "oauth_access_token": "xxxxxxxx",         # app_key in Dropbox developer page
  "output": "/hass_b3_backup/",                 # folder created under Application in Dropbox
  "keep_last": 7
}
```

Is my config correct?

Where should I check to solve this problem?

I've already checked for space available on Dropbox and I have more than 2GB.
Maybe anything related to the folder.
I've created the folder named hass_b3_backup under the Applications folder.
Is it correct?

Thanks

**Comment by kjdijkema** [comment]
I have the same problem:

```
{"command": "upload"}
[Info] Received message with command upload
[Info] Uploading all .tar files in /backup (skipping those already in Dropbox)
 > Uploading "/backup/xxx.tar" to "/xxx.tar"... FAILED
An error occurred requesting /upload
```
The add-on has worked for a week without problems but now it's only giving this error.

Enough space on Dropbox -> check
hass.io up-to-date -> check
all other add-ons up-to-date -> check

**Comment by woody4165** [comment]
Thanks @kjdijkema 
It worked for me also.

I will close this issue.

**Comment by tjourdan** [comment]
I couldn't get it to run. The error message is always similar to the ones mentioned above 
> by 6 chunks *** FAILED
>An error occurred requesting /chunked_upload
I was exchanging tolken and everything - but never worked :-(
Can anybody help me?
