### ISSUE TITLE
upload different file extensions

### ISSUE THREAD

**Issue by nmsoares** [danielwelch/hassio-dropbox-sync#2]
Hi,
is there a way to use your add-on not only to upload TAR files but also other file extensions ?
Thanks!

**Comment by danielwelch** [comment]
What's your use case for this? It's definitely possible. As of now, the add-on only mounts the `backup` directory and there typically isn't anything in there but `.tar` files generated by the snapshot process (as far as I know).

**Comment by nmsoares** [comment]
@danielwelch Can you help adding an option for selecting file extensions ?
Thanks!

**Comment by danielwelch** [comment]
@nmsoares I'm working on this now, should have a way to do this soon. 

The way I'm implementing it exposes an option `filetypes` that will allow you to specify extensions to match in the following format: `"png|jpg|gif"`
The add-on will then scan the `/share` folder for files with those extensions and upload them to dropbox at `$output`. 

Does that sound good?

**Comment by danielwelch** [comment]
@nmsoares this is available as described above in the upcoming [v1.2.0](https://github.com/danielwelch/hassio-dropbox-sync/releases/tag/v1.2.0) release. Should be available today.
