### ISSUE TITLE
Keep On Dropbox

### ISSUE THREAD

**Issue by sagitt** [danielwelch/hassio-dropbox-sync#28]
is possible to set how many backup still stay on dropbox and delete olds?

if not, maybe add an option?

**Comment by d0ugal** [comment]
See [`keep_last`](https://github.com/danielwelch/hassio-dropbox-sync#configuration), I think that does what you need.

**Comment by sagitt** [comment]
> See [`keep_last`](https://github.com/danielwelch/hassio-dropbox-sync#configuration), I think that does what you need.

keep last is for local snapshot, right?

**Comment by d0ugal** [comment]
> > See [`keep_last`](https://github.com/danielwelch/hassio-dropbox-sync#configuration), I think that does what you need.
> 
> keep last is for local snapshot, right?

Oh, maybe. Sorry. I don’t actually use this add on but I thought it limited both local and in Dropbox. That’s how I implemented it in mine (trying to copy this one!) 😂

**Comment by svh1985** [comment]
I love to have this feature too! **keep_last_dropbox**

**Comment by mattlward** [comment]
I would love to see **keep_last_dropbox** become a thing as well.  I am paranoid and keep copies on dropbox, google drive and my own internal pi running samba.

To bad, the dates on everything almost look like this project has been abandoned. 

But, 2 offsite and one onsite backups are good policy.
