### ISSUE TITLE
keep_days option doesn't remove any local snapshots

### ISSUE THREAD

**Issue by cjramseyer** [danielwelch/hassio-dropbox-sync#33]
Running HA 0.109.6 on rPi 3B+
Latest version of the addon.

The addon documentation lists keep_days as will remove local snapshots older than the specified number of days.  The addon has removed anything.
It would be nice for this feature to work so it doesn't fill up the SD Card.

**Comment by cjramseyer** [comment]
This continues to be an issue.  There is no service call in HA to delete old snapshots.  Is this being worked on?
Running HA 0.118.4

**Comment by Ndrinta** [comment]
I don't think so. Unfortunately

**Comment by cjramseyer** [comment]
I won't be using this plugin any longer.  I don't have time to keep deleting snapshots to free disk
