### ISSUE TITLE
Unable to add it to HACS

### ISSUE THREAD

**Issue by Ndrinta** [danielwelch/hassio-dropbox-sync#37]
Hi, just tried to add the repo to my HACS and this is the error message I get:
Repostitory structure for master is not compliant
What could I try to solve this?
![Screenshot_20200816-155317](https://user-images.githubusercontent.com/4704172/90337171-a442e980-dfd8-11ea-8b57-1005fc7afca1.png)

Cheers to anyone willing to help me! 😃

**Comment by jane-t** [comment]
Just to confirm I have the same problem.  Running latest Home Assistant and HACS as I only built the system yesterday.

**Comment by hw-monkey** [comment]
Many months later, same problem. too bad because this would be useful

**Comment by clomads** [comment]
HACS doesn't do add-ons, you gotta add the repo to the Add-on Store in supervisor
