### ISSUE TITLE
no such backup file?

### ISSUE THREAD

**Issue by kasper1221** [danielwelch/hassio-dropbox-sync#7]
i've just installed the add-on and all but i get this error. what did i do wrong or did i forget something?

starting version 3.2.4
[Info] Files will be uploaded to: /hasssio-backups/
[Info] Saving OAUTH_ACCESS_TOKEN to /etc/uploader.conf
[Info] Listening for messages via stdin service call...
{"command": "upload"}
[Info] Received message with command upload
[Info] Uploading all .tar files in /backup (skipping those already in Dropbox)
 > No such file or directory: /backup/*.tar
Some error occured. Please check the log.

**Comment by danielwelch** [comment]
Just eliminating the obvious first, do you have any backups?

**Comment by kasper1221** [comment]
That's a good one... I don't think i have. Do you have to do this manually?

**Comment by danielwelch** [comment]
No worries! I'd read a little about hass.io backups and then how to automate backups with timed service calls, then automate this add-on (again with a service call, see the README) if you're interested.
